package:
    name:           reodb
    headline:       reODB
    title:          Reusable objective database
    type:           project
    keywords:       SQL, EAV

require:
    hiqdev/hidev-hiqdev: "*"
    hiqdev/hidev-sql:    "*@dev"
