package:
    type:           project
    name:           reodb
    title:          Reusable objective database
    headline:       reODB
    keywords:       SQL, EAV

require:
    hiqdev/hidev-hiqdev: "*"
    hiqdev/hidev-sql:    "*@dev"
